{% set goname = "github.com/grafana/k6" %}
{% set version = "1.2.1" %}

{% set name = goname.split('/')[-1] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 6976de6fb52b09b84fe5b1d849dc6b197cb9127a682a12beb2be70eca74b39cc

build:
  script:
    - go build -trimpath -ldflags "-s -w" -o $PREFIX/bin/  # [unix]
    - go build -trimpath -ldflags "-s -w" -o %LIBRARY_BIN%/  # [win]
    - go-licenses save . --save_path="./license-files/" --ignore go.k6.io/k6 --ignore github.com/grafana --ignore buf.build/gen/go
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} version

about:
  home: https://{{ goname }}
  summary: 'A modern load testing tool, using Go and JavaScript'
  description: |
    k6 is a modern load-testing tool, built on our years of experience in the performance and testing industries. It's built to be powerful, extensible, and full-featured. The key design goal is to provide the best developer experience.
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE.md
    - license-files/

extra:
  recipe-maintainers:
    - seowalex
